### ISSUE TITLE
pa11y and HTMLcodesniffer giving different results

### ISSUE THREAD

**Issue by nickcall** [pa11y/pa11y#142]
An issue was raised in pa11y-dashboard which relates more to pa11y https://github.com/springernature/pa11y-dashboard/issues/97 thus raising the issue here

**Further info after looking into the original ticket**
Having tested http://www.nature.com/nplants from both pa11y using the cmd line and in a browser with HTMLcodesniffer you get very different results :-

**Cmd line (pa11y)** - 7 Errors / 72 Warnings / 243 Notices
**Browser (HTMLcodesniffer)** - 21 Errors / 83 Warnings / 252 Notices

We assumed this might be something to do with ads etc so used the -hide-element tag to hide ads, in effect to check if pa11y even looked at them and we got the same results.

**Cmd line with ads hidden (pa11y)** 7 Errors / 73 Warnings / 243 Notices

From this we concluded that pa11y is not following iframes and thus not getting the errors created by ads etc, we assume this is something to do with phantomjs https://groups.google.com/forum/#!searchin/phantomjs/iframe, now we get to the questions...

1. What is the relationship between HTMLcodesniffer and Phantomjs should they be solving this issue, it's all working fine in the browser so why when we using it in pa11y does it not work.

2. Could we add http://phantomjs.org/api/command-line.html --web-security=[true|false]) which enables web security and forbids cross-domain XHR (default is true). Also accepted: [yes|no] to the phantomjs config or is that a really bad idea, we 'think' this may then allow us to follow iframe code

**Comment by hollsk** [comment]
We've been looking at this today. Adding `web-security: false` to the PhantomJS parameter list doesn't really make a difference on its own, though from what I can tell it _is_ one part of the puzzle, at least for situations involving CORS. 

There's some suggestion [citation needed] that it's necessary to recursively load in content from iframes during `page.evaluate()`, making use of the webpage API module method `switchToFrame()`. Unfortunately it's poorly documented and I can't make much sense of how to use it: http://phantomjs.org/api/webpage/method/switch-to-frame.html - though it doesn't help that I'm not sure how PhantomJS and the inject.js methods are designed to interact, so I'm not even confident that this is what we need to do in the first place.

**Comment by hollsk** [comment]
There is a sister issue here: https://github.com/squizlabs/HTML_CodeSniffer/issues/109

HTML Code Sniffer has a CLI tool as well as a bookmarklet. We've tested against the CLI tool and found that it gives consistent results with Pa11y. As noted in the sister issue, HTML Code Sniffer and Pa11y both use PhantomJS to evaluate pages. The explanation given by @lwright-sq there pretty much covers it - we're limited to what Phantom can give us at the command line. The HTML Code Sniffer bookmarklet runs in a different environment (your browser), so could easily pick up things that the CLI tools don't have access to. 

Regarding iframes more specifically - Phantom ​_does_​ let us access the contents of iframes, but it's tricky, and due to the way Pa11y works we'd really be looking at a major rewrite to support providing reports on their contents. Because iframe contents are so often out of our control (ads, third party widgets, etc) we're ok with Pa11y not reporting on these directly; if you really need to test against an iframe's source, then you can give Pa11y that source URL separately.

**Comment by JordanGS** [comment]
I was about to create a ticket for this as well. I have been using pa11y now to various sites and confirming the results with code sniffer. However as mentioned in the original report, the results do not match up. So i can validate that the OP's report of inconsistency.

**Comment by hollsk** [comment]
Hey @JordanGS - are you able to confirm you're finding that the results are different between Pa11y and the HTML Code Sniffer command line tool? The like-for-like tests we've run have given the same results (NB: like-for-like tests are command line only, we can't really compare a CLI tool against a bookmarklet for the reasons given above).

If you have some sample URLs where Pa11y's results don't match those of HTML Code Sniffer's command line tool results, I'd like to see them so that we can take another look.

**Comment by JordanGS** [comment]
@hollsk I'm on break till the 5th of May and i currently don't have access to any of the internal sites i was testing. I will test and compare both command line tools when I am back.

**Comment by nickcall** [comment]
Hi @JordanGS , We’ve done some analysis on why there can be differences between Pa11y/Pa11y dashboard and the HTML CodeSniffer bookmarklet.

We’ve documented the differences and reasons for them in the common questions [https://github.com/pa11y/pa11y/blob/master/README.md#common-questions] section of the Pa11y readme. I hope this helps to clarify the issue.
