### ISSUE TITLE
Authentication with Pa11y and multiple redirects.

### ISSUE THREAD

**Issue by qaDream77** [pa11y/pa11y#162]
Hello @GlynnPhillips @rowanmanning 

I have having some issues with authentication and redirects.

Login portal: https://mysite.ca/admin.html
First Page after successful login: https://mysite.ca/admin/news.html
Desired Page: https://mysite.ca/admin/contact.html

**config.js:**
```
module.exports = {
    beforeScript: function(page, options, next) {
        var waitUntil = function(condition, retries, waitOver) {
            page.evaluate(condition, function(error, result) {
                if (result || retries < 1) {
                    waitOver();
                } else {
                    retries -= 1;
                    setTimeout(function() {
                        waitUntil(condition, retries, waitOver);
                    }, 200);
                }
            });
        };

        page.evaluate(function() {
        document.getElementById("username").value = "testuser";
        document.getElementById("password").value = "pwd123";
        document.getElementById("submit").click();

        }, function() {
            waitUntil(function() {
                return window.location.href === 'https://mysite.ca/admin.html';
            }, 20, next);
        });
    }
}
```

**Command to Run:**
`pa11y --config config.js "https://mysite.ca/admin/contact.html"`

**The Problem:**
If you manually go to the website, it will take you to the login page (`admin.html`), the next page after login is **ALWAYS** `news.html`, I have no control over this. However, the page I am trying to actual have pa11y scan is `contact.html`.

**My Question:**
How do I do another redirect in this case, I am successfully authenticated but i am stuck on `news.html` and it does not go to `contact.html`

**Comment by GlynnPhillips** [comment]
Hi @qaDream77 

You will need to script the redirect manually yourself once the login has completed, this can easily be done with two separate calls to the `waitUntil` function. There are a couple other things that will prevent the above example from working which we can fix at the same time.

In the above example you are waiting until `window.location.href` equals `https://mysite.ca/admin.html` which will happen as soon as you are redirected from `https://mysite.ca/admin/contact.html` to `https://mysite.ca/admin.html` meaning the script you have written to login will never run. You need to wait until  `window.location.href` equals `https://mysite.ca/news.html` instead as this is the page that is loaded when the login is successful.

As the site will always redirect to `admin.html` on initial load you should also use the following command to run `pa11y` as well instead of the command you supplied above as this will save the hassle of having to wait for another redirect.

`pa11y --config config.js "https://mysite.ca/admin.html"`


```js
module.exports = {
    beforeScript: function(page, options, next) {
        var waitUntil = function(condition, retries, waitOver) {
            page.evaluate(condition, function(error, result) {
                if (result || retries < 1) {
                    waitOver();
                } else {
                    retries -= 1;
                    setTimeout(function() {
                        waitUntil(condition, retries, waitOver);
                    }, 200);
                }
            });
        };

        page.evaluate(function() {
            document.getElementById("username").value = "testuser";
            document.getElementById("password").value = "pwd123";
            document.getElementById("submit").click();
        }, function() {
            waitUntil(function() {
                // Wait until the login has been success and the /news.html has loaded
                return window.location.href === 'https://mysite.ca/admin/news.html';
            }, 20, function() {
                // Redirect to the page contact.html page
                window.location = 'https://mysite.ca/admin/contact.html';
                waitUntil(function() {
                    // Wait until the contact.html has been loaded before running pa11y
                    return window.location.href === 'https://mysite.ca/admin/contact.html';
                }, 20, next);
            });
        });
    }
}
```

**Comment by qaDream77** [comment]
@GlynnPhillips with update three, what is my command to run pally now? Is it the one from update two or has it changed? Thanks :)

**Comment by GlynnPhillips** [comment]
@qaDream77 Sorry the ordering of that explanation is not very clear. Yes the command would be the one mentioned in update 2

`pa11y --config config.js "https://mysite.ca/admin.html"`

**Comment by qaDream77** [comment]
@GlynnPhillips Will try as soon as i get in, thanks a lot!

**Comment by qaDream77** [comment]
@GlynnPhillips 

```
Welcome to Pa11y

 > PhantomJS browser created
 > Testing the page "https://mysite.ca/admin.html"
/home/userid/Documents/Accessibility/MYSITE TEST/config.js:26
                window.location = 'https://mysite.ca/admin/contact.html';
                ^

ReferenceError: window is not defined
    at /home/userid/Documents/Accessibility/MYSITE TEST/config.js:26:17
    at /home/userid/Documents/Accessibility/MYSITE TEST/config.js:6:21
    at /home/userid/.linuxbrew/lib/node_modules/pa11y/node_modules/node-phantom-simple/node-phantom-simple.js:69:18
    at IncomingMessage.<anonymous> (/home/userid/.linuxbrew/lib/node_modules/pa11y/node_modules/node-phantom-simple/node-phantom-simple.js:628:9)
    at emitNone (events.js:91:20)
    at IncomingMessage.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:926:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by GlynnPhillips** [comment]
@qaDream77 sorry my bad, I didn't test what I wrote and I forgot that in order to redirect the page using `window.location.href` you would need to be doing this against the `phantomjs` `page` instance.

**Updated version**

```js
module.exports = {
    beforeScript: function(page, options, next) {
        var waitUntil = function(condition, retries, waitOver) {
            page.evaluate(condition, function(error, result) {
                if (result || retries < 1) {
                    waitOver();
                } else {
                    retries -= 1;
                    setTimeout(function() {
                        waitUntil(condition, retries, waitOver);
                    }, 200);
                }
            });
        };

        page.evaluate(function() {
            document.getElementById("username").value = "testuser";
            document.getElementById("password").value = "pwd123";
            document.getElementById("submit").click();
        }, function() {
            waitUntil(function() {
                // Wait until the login has been success and the /news.html has loaded
                return window.location.href === 'https://mysite.ca/admin/news.html';
            }, 20, function() {
                // Redirect to the page contact.html page
                page.evaluate(function() {
                    window.location.href = 'https://mysite.ca/admin/contact.html';
                });
                waitUntil(function() {
                    // Wait until the contact.html has been loaded before running pa11y
                    return window.location.href === 'https://mysite.ca/admin/contact.html';
                }, 20, next);
            });
        });
    }
}
```

**Comment by qaDream77** [comment]
@GlynnPhillips Thanks a lot man! I learned a lot through your script. I was having trouble with this because I get confused how to write these config files for pa11y. I have a hard time translating my normal javascript functions. It works great now :)

**Comment by GlynnPhillips** [comment]
@qaDream77 no problem and always happy to help.

I can understand your desire to have the correct url referenced in the command line output. Using the current or previous versions of `pa11y` the only way to do this would be to alter the `beforeScript` to handle this extra redirect. However if @rowanmanning agree's we might be able to make a change in a future version to output the final url rather than the originally url that is passed to the command. I have raised an issue (#164) for us to discuss this in more detail.

**Page load flow**
To help you understand how `pa11y` and the `beforeScript` works here is a high level explanation of the flow for your example.

The command `pa11y --config config.js "https://mysite.ca/admin.html"` is run
&#9660;
`Pa11y` loads the initial page (`admin.html`) in a `Phantomjs` window
&#9660;
`beforeScript` starts to run
&#9660;
`beforeScript` handles logging into the site
&#9660;
`beforeScript` handles waiting until the login is success and the `news.html` page has loaded
&#9660;
`beforeScript` handles redirecting / loading the `contact.html`
&#9660;
`beforeScript` is now complete and `pa11y` then tests the `contact.html` page

Hopefully this will help you understand how `pa11y` handles your scenario.

**Comment by qaDream77** [comment]
@GlynnPhillips Thank you! That helps a lot. Which is good news for me because in my case the start and end url can be the same thing because I have an automatic redirect if the user is not authenticated! =D

@JordanGS take a look at this mate.

**Comment by JordanGS** [comment]
@qaDream77 Yup, I’ve been keeping track of it! Thanks for creating the ticket.

@GlynnPhillips Thank you for the clear explanation, that helps me a great deal.

**Comment by GlynnPhillips** [comment]
Great, glad its helped. I am going to close this issue now but feel free to open issues if you need further help in the future.

**Comment by JordanGS** [comment]
@GlynnPhillips So we've both been working on this and there seems to be an interesting issue. I am trying to use the same template script to authenticate into everything. However if my first page after successful login and my desired page are the same, pa11y won't properly evaluate the page. I'm unsure as to why. Trying to use the same JS script for everything, even if having a redirect in this case is redundant.

Login portal: https://mysite.ca/admin.html
First Page after successful login: https://mysite.ca/admin/news.html
Desired Page: https://mysite.ca/admin/news.html
