### ISSUE TITLE
Follow up to issue #162: Authentication with Pa11y and multiple redirects

### ISSUE THREAD

**Issue by JordanGS** [pa11y/pa11y#167]
**Reference:** #162

@GlynnPhillips So we've both been working on this and there seems to be an interesting issue. I am trying to use the same template script to authenticate into everything. However if my first page after successful login and my desired page are the same, pa11y won't properly evaluate the page. I'm unsure as to why. Trying to use the same JS script for everything, even if having a redirect in this case is redundant.

Login portal: https://mysite.ca/admin.html
First Page after successful login: https://mysite.ca/admin/news.html
Desired Page: https://mysite.ca/admin/news.html

**Update:** Sample config.js
```
module.exports = {
    beforeScript: function(page, options, next) {
        var waitUntil = function(condition, retries, waitOver) {
            page.evaluate(condition, function(error, result) {
                if (result || retries < 1) {
                    waitOver();
                } else {
                    retries -= 1;
                    setTimeout(function() {
                        waitUntil(condition, retries, waitOver);
                    }, 200);
                }
            });
        };

        page.evaluate(function() {
            document.getElementById("username").value = "testuser";
            document.getElementById("password").value = "pwd123";
            document.getElementById("submit").click();
        }, function() {
            waitUntil(function() {
                // Wait until the login has been success and the /news.html has loaded
                return window.location.href === 'https://mysite.ca/admin/news.html';
            }, 20, function() {
                // Redirect to the page contact.html page
                page.evaluate(function() {
                    window.location.href = 'https://mysite.ca/admin/news.html';
                });
                waitUntil(function() {
                    // Wait until the contact.html has been loaded before running pa11y
                    return window.location.href === 'https://mysite.ca/admin/news.html';
                }, 20, next);
            });
        });
    }
}
```

Command to run: 
`pa11y --debug --config config.js "https://mysite.ca/admin.html"`

How do i know that it doesn't work? Because when i run the original script, that you can see above (in the first post), i can find elements related to the `news.html` page.

**Update 2:** Sample config.js
```
module.exports = {
    beforeScript: function(page, options, next) {
        var waitUntil = function(condition, retries, waitOver) {
            page.evaluate(condition, function(error, result) {
                if (result || retries < 1) {
                    waitOver();
                } else {
                    retries -= 1;
                    setTimeout(function() {
                        waitUntil(condition, retries, waitOver);
                    }, 200);
                }
            });
        };

        page.evaluate(function() {
            document.getElementById("username").value = "testuser";
            document.getElementById("password").value = "pwd123";
            document.getElementById("submit").click();
        }, function() {
            waitUntil(function() {
                // Wait until the login has been success and the /news.html has loaded
                return window.location.href === 'https://mysite.ca/admin.html';
            }, 20, function() {
                // Redirect to the page contact.html page
                page.evaluate(function() {
                    window.location.href = 'https://mysite.ca/admin/news.html';
                });
                waitUntil(function() {
                    // Wait until the contact.html has been loaded before running pa11y
                    return window.location.href === 'https://mysite.ca/admin/news.html';
                }, 20, next);
            });
        });
    }
}
```

and i change the run command to: `pa11y --debug --config config.js "https://mysite.ca/admin/news.html"`, then it works for this page but not the other's.

**Update 3:** I can also remove the redirect in this matter for it to work.
```
module.exports = {
    beforeScript: function(page, options, next) {
        var waitUntil = function(condition, retries, waitOver) {
            page.evaluate(condition, function(error, result) {
                if (result || retries < 1) {
                    waitOver();
                } else {
                    retries -= 1;
                    setTimeout(function() {
                        waitUntil(condition, retries, waitOver);
                    }, 200);
                }
            });
        };

        page.evaluate(function() {
            document.getElementById("username").value = "testuser";
            document.getElementById("password").value = "pwd123";
            document.getElementById("submit").click();
        }, function() {
            waitUntil(function() {
                // Wait until the login has been success and the /news.html has loaded
                return window.location.href === 'https://mysite.ca/admin/news.html';
            }, 20, function() {
                // Redirect to the page contact.html page
                page.evaluate(function() {
                    window.location.href = '';
                });
                waitUntil(function() {
                    // Wait until the contact.html has been loaded before running pa11y
                    return window.location.href === '';
                }, 20, next);
            });
        });
    }
}
```

and i change the run command to: `pa11y --debug --config config.js "https://mysite.ca/admin/news.html"`. Now it would work for everything but it's a bit confusing i think.

I am just wondering why this happens, i read the post where you explained the work flow and it shouldn't matter that it is redirecting to the same page.

I am fine with running it like the script in **update 3**, i just wanted to update in case someone else had a similar issue. But if you have any idea as to why this happens because as far as i can tell, it really shouldn't matter.

**Comment by GlynnPhillips** [comment]
Hi @JordanGS,

Can I just make sure I am following this correctly before I respond in full else I may just complicate / confuse things.

You want to use Pa11y to test `https://mysite.ca/admin/news.html` and this also happens to be the same page that you are redirected too when you are successfully logged in? 

Glynn

**Comment by JordanGS** [comment]
@GlynnPhillips Yes, i know it sounds redundant but i wanted to use a single template for the process for a list of URL's.

**Comment by GlynnPhillips** [comment]
@JordanGS Ok now I understand the problem you are having. Your problem is that this config was designed specifically for the scenario given in your previous issue. If you want to be able to use one config for multiple different urls your config will need to be more dynamic than this.

Unless someone knows phantomJs better than me, I think there are two options (sort of) to do this.

1) Having multiple config files for each test run. Then using whatever you are currently using to automate running pa11y to be clever enough to pick the correct config for the relevant url.

2) If the `beforeScript` knew of the original url that was passed to pa11y it could use that and then it could dynamically figure out where to go after the login has happened.

- In this case you would call pa11y using `https://mysite.ca/admin/news.html` this would be redirect (by your site) to `https://mysite.ca/admin/admin.html`. 

- Your `beforeScript` would then handle logging you in.

- Your   `beforeScript` could then use the original url passed to the command (`https://mysite.ca/admin/news.html`) to decide if you needed to do any further redirects or if its ok to run pa11y now. In this case it would not redirect anywhere else as its the same page that you are already redirected to after login. However if your initail command was passed `https://mysite.ca/admin/example-page.html` the `beforeScript` could then redirect to `https://mysite.ca/admin/example-page.html` after the login.

Heres the bad news, that second options is currently not possible in pa11y (again unless someone knows something I don't that could be done in your config to get the original url). I am going to raise this feature in the issues and let people decide if its something we want to do.

For now I suggest you just have multiple config files for each test run.

**Comment by JordanGS** [comment]
@GlynnPhillips Thanks, i was thinking the same thing. I'll upload my script once it's done.

**Comment by GlynnPhillips** [comment]
@JordanGS I'm going to close this issue now and if in the future we work on anything that might make this easier for you I will be remember to notify you.
