### ISSUE TITLE
Hide warnings and notices by default

### ISSUE THREAD

**Issue by rowanmanning** [pa11y/pa11y#170]
I'm not a fan of the warnings and notices that Pa11y outputs. They're not really actionable, and they add quite a bit of noise to the reports. I'm wondering whether we should exclude them.

There are two options I can see:
1. Exclude them by default, but allow them to be enabled with something like `--include warnings`
2. Exclude them always, so you will never see them

Option 2 has the advantage of simplifying the code and allowing us to remove things like the `--level` flag which is all about tweaking what Pa11y should do when it encounters warnings.

Either way this would be a breaking change – something to consider for Pa11y 5.0.

**Comment by hollsk** [comment]
Excluding by default but allowing the option would be my preference. Although they're not always actionable, warnings and notices _are_ useful as general information for people who might not otherwise know (stuff like "click here" is a terrible text label for a link, for e.g.). 

Also I think the existence of warnings and errors is really just an indication of _Pa11y_ not being able to test the particular item. That doesn't mean that Pa11y would never be able to test a particular thing, if we did ever make it possible to use a plugin system of some sort, or wrote in stricter checks. I also think it's better to be clear about Pa11y's limitations, and the notices and warnings do that, to an extent.

**Comment by typothecary** [comment]
We should write a blog post about why "click here" is bad, because it's annoyingly effective from a marketing p-o-v. (it gets good results when used in marketing emails)

**Comment by JordanGS** [comment]
@rowanmanning I don't like the idea of excluding anything by default, everything should be included by default. But that is just my preference.

**Comment by hollsk** [comment]
As core developers, we do a _lot_ more testing of URLs than most users do, and we're often not even interested in the results, per se - we're just trying to replicate situations across methods and setups. It's really annoying to have to do that 50 times a day and always remember to switch off notices and warnings. Our use case is often pretty different to the use case of other people. What if we used a dotfile configuration for power users to set default options?

@typothecary maybe open another issue about blog posts? We haven't set a blog up because we didn't feel like we'd be able to produce enough content, but it's worth an open discussion.

**Comment by rowanmanning** [comment]
Gonna revive this conversation. I still think that excluding warnings/notice by default would be a good move and mean that Pa11y only ever gives you directly _actionable_ feedback. Agree that there would have to be a way to include warnings/notices back in.

Potentially we just add notices/warnings to the default `ignore` option and then people can override by specifying an empty `ignore`.

**Comment by hollsk** [comment]
I'm still comfortable with the idea of doing this, fwiw. I almost never care about notices or warnings. 

We're not really taking anything away, after all - just changing the initial parameters.

**Comment by andrewmee** [comment]
I'd also support not showing notices/warnings by default.  I suspect everyone ignores them anyway, so better to more easily support that behaviour (while obviously continuing to document that you can't just rely on pa11y saying there are no errors, yadda yadda)
