### ISSUE TITLE
Trouble with including functions within page.evalutate - scope issue?

### ISSUE THREAD

**Issue by PhillyWebGuy** [pa11y/pa11y#185]
I'm trying to make my code a bit more modular and reusable, and am thus including code I intend upon using in numerous tests in external files. My config file looks as such. 

``` Javascript
var extend = require('node.extend');
var pa11y = require('../../../..');
var myPa11y = require('../../../support/my-pa11y.js');

var pa11yObj = extend(true, myPa11y, {
    beforeScript: function(page, options, next) {
        page.evaluate(function() {
//Note: This doesn't work
            myPa11y.login();
        }, function() {
//Note: This does work
            myPa11y.waitUntil(function() {
                return window.location.href === 'https://demo.xxxxxxxx.com/dashboard';
            }, 100, next, page);
        });
    }
});

var test = pa11y(pa11yObj);

test.run('https://demo.xxxxxxxxxx.com/', function(error, result) {
    if (error) {
        return console.error(error.message);
    }
    console.log(result);
});
```

The code inside my-pa11y.js looks like this:

``` javascript
module.exports = {
    ignore: [
        'notice', 'warning'
    ],
    wait: 1000,
    login: function() {
        var user = document.querySelector('#LoginFormUserName');
        var password = document.querySelector('#LoginFormPassword');
        var submit = document.querySelector('#login_button');
        user.value = 'xxxxxxxxxx;
        password.value = 'xxxxxx;
        submit.click();
    },
    allowedStandards: ['Section508'],
    standard: 'Section508',
    // Log what's happening to the console
    log: {
        debug: console.log.bind(console),
        error: console.error.bind(console),
        info: console.log.bind(console)
    },
    waitUntil: function(condition, retries, waitOver, page) {
        var self = this;
        page.evaluate(condition, function(error, result) {
            if (result || retries < 1) {
                waitOver();
            } else {
                retries -= 1;
                setTimeout(function() {
                    self.waitUntil(condition, retries, waitOver, page);
                }, 10000);
            }
        });
    }
};
```

The problem I am having is that the myPa11y.login() never seems to execute. But I copy and paste that code within the function and place within the page.evaluate() block, it works and the script will login as desired.

I suspect there is some scope issue I am not understanding here. I don't know if this is a JavaScript question or a pa11y question, but was wondering if someone could point me in the right direction.

**Comment by rowanmanning** [comment]
Hi @PhillyWebGuy. Yes the issue here is that the beforeScript function is run in a PhantomJS context, and your reusable functions are in a Node.js context. PhantomJS code can't directly call Node.js code as they don't share the same scope. Does that make sense?

Unfortunately this is a limitation of the way Node.js interacts with PhantomJS. One workaround you could try is to save your `login` and `waitUntil` functions to separate files and then use `injectJs` within your `beforeScript` function. Like this: https://github.com/pa11y/pa11y/blob/master/lib/pa11y.js#L92

I hope this helps, apologies for the confusion. I'm going to close this issue but will continue to respond if you need a little help with `injectJs`.
