### ISSUE TITLE
Investigate Replacing PhantomJS with headless Chrome

### ISSUE THREAD

**Issue by josebolos** [pa11y/pa11y#258]
- [ ] Placeholder.
- [ ] Edit this in order to add a list of all the things that need to happen so we can replace PhantomJS.

**Comment by rowanmanning** [comment]
As a starting point, [we could use this library](https://github.com/cyrus-and/chrome-remote-interface). There are a couple of important things that need to be available IMO if we're going to switch to Headless Chrome:

  1. It needs to be easily done with Node.js (seems it is based on library linked above)
  2. It needs to be able to support _all_ of the current Pa11y functionality (I don't really want to remove any features for 5.x)
  3. It needs to be installable through npm, like we do with PhantomJS. Ideally so we can control which version is being used, and so that people don't have a second install step.

**Comment by TheJaredWilcurt** [comment]
`#3` would be nice because no OS ships with Chrome except ChromeOS. People shouldn't be required to install an extra browser globally on their OS just to run Pa11y. I don't even think you can get Chrome on Ubuntu, just Chromium.

**Comment by aweingarten** [comment]
The maintainer of PhantomJs Stepped down a few months back due to headless chrome.  Phantom seems dead as a project.  It doesn't seem like there are too many options Pa11y will need to switch.

> I think people will switch to it, eventually. Chrome is faster and more stable than PhantomJS. And it doesn't eat memory like crazy.

https://groups.google.com/forum/#!searchin/phantomjs/chrome%7Csort:relevance/phantomjs/9aI5d-LDuNE/MpCM_wACAQAJ

**Comment by rowanmanning** [comment]
An update on this, we're investigating using [Puppeteer](https://github.com/GoogleChrome/puppeteer#readme)

**Comment by rowanmanning** [comment]
Yet another update: a version of Pa11y using Headless Chrome is available here #304

It won't make it into `master` for a little while, but we'll hopefully be releasing a v5 beta of Pa11y soon. If you want to help out then reviewing parts of the PR above would be super helpful :)

**Comment by andrewmee** [comment]
I'm going to close this as I feel @rowanmanning's gone well past the point of investigating, and is well on track to complete this!
