### ISSUE TITLE
Timeout working inconsistently

### ISSUE THREAD

**Issue by micahsaul** [pa11y/pa11y#274]
It appears that the timeout flag only works if the timeout is shorter than the time it takes for the actual scan to start?

When I run, say `pa11y nationalhousing.gov --timeout=7000`, the process times out as expected.

When I run `pa11y nationalhousing.gov --timeout=70000`, the process hangs indefinitely. (Side note, nationalhousing.gov has a 301 redirect which seems to cause pa11y to hang).

The cut off point seems to be when ` > Testing the page "http://nationalhousing.gov"` is displayed. If the timeout is shorter than the time it takes to get that message, truffler will time out. Once that message is displayed, however, game over.

Thanks for the great tool, btw, and please let me know if I can help you track this down further. I have a big ol' pile of URLs that are causing pa11y to hang the same way as nationalhousing.gov, as well if that's useful to you.

**Comment by hollsk** [comment]
Hi @micahsaul - glad you're enjoying Pa11y! 

This is quite a interesting problem. It also shows up if you use the --wait flag instead of the --timeout flag.

Looks like Pa11y executes fine right up until this line: https://github.com/pa11y/pa11y/blob/master/lib/inject.js#L29 - the setTimeout doesn't get executed, so CodeSniffer never runs, and the tests just hang without starting. I wonder if there's some kind of timer conflict, as your page sets a timer in the body onload... but the timer IDs should be unique already, so I can't really see why that would be a problem 🤔 

Could we see a selection of your other failing URLs, please? 😄

**Comment by micahsaul** [comment]
Hmm... so, it seems like the only URLs that are consistently failing in this way are all redirects to HUD's website. So, there might be something weird that they're doing specifically in the way they've implemented those redirects.

nationalhousing.gov
nationahousinglocator.gov
disasterhousing.gov
nls.gov

If I find more, I will drop them in here. The others I had that were failing seem to be a different issue, probably on my end.

**Comment by hollsk** [comment]
Hm. The only thing, though - if I run Pa11y against the HUD portal homepage URL directly, it hangs there too, even though there's no server redirect. It suggests to me that there's something up at the end target URL rather than any of the redirects that take you there. 

I've tried running Pa11y on a few random pages in the HUD portal, and I'm suspecting a javascript timer conflict more and more. If you try running against the Press Room -> Speeches, Remarks, Statments or Press Room -> Archived Speeches, everything is fine. On other pages, it's not. 

The pages that hang all have a `startBoxTimer();` method in the body onload, and the ones that _don't_ hang don't have that. 

I wonder if the problem is in `rotateboxes.js`

`startBoxTimer()` runs this function:

```function StopTheClock()
{
    if(timerRunning)
        clearTimeout(timerID);
    timerRunning = false;
}```

`timerID` is set in the global scope. I'm thinking that maybe Pa11y's timeout is being affected by the box timer, and the two are interfering with each other. 

If you have access to the HUD codebase, maybe you could try scoping those variables more safely, see if it makes a difference?

**Comment by micahsaul** [comment]
Alas, I don't have access to their codebase.

For awareness, I'm working on https://github.com/18F/pulse, trying to add a scan of a11y issues to the existing https and analytics participation scans we're currently running across the entire federal .gov space.

I think for now, I'm going to work around the issue by just blacklisting the sites that are locking. Thanks for looking into this for me!

**Comment by hollsk** [comment]
Wow, that's a _massive_ project! It's making me think the team at my org. could really use something similar 😄 

We've been looking at this timeout problem again today, to see if there's anything we can do on our end, as obviously it's not ideal. @rowanmanning just realised that the HTML_Codesniffer bookmarklet also crashes on the same URLs, and since we rely on HTML_Codesniffer in Pa11y, that's probably the origin of the problem.  

It'd be worth you opening a ticket in the [HTML_Codesniffer project](https://github.com/squizlabs/HTML_CodeSniffer) to ask them to take a look at it, as maybe there's something they can do. If it's something they can fix then the fix will also be available to Pa11y.

**Comment by josebolos** [comment]
Hi @micahsaul, are you still experiencing this problem?

Feel free to reopen the issue if that's the case and we'll have a look!
