### ISSUE TITLE
Add a JUnit reporter

### ISSUE THREAD

**Issue by scottconnerly** [pa11y/pa11y#276]
In addition to the existing reporters, it would be useful to have a JUnit XML reporter. Adding this output format would increase the ease with which pa11y could be integrated in a CI server like Jenkins, CircleCI or Bamboo.

Documentation on the file format: http://llg.cubic.org/docs/junit/ 

I don't have a PR ready for this, only just now identified the need. Would welcome assistance in this endeavor.

**Comment by hollsk** [comment]
Hi @scottconnerly - thanks for using Pa11y! 

I think this is the kind of thing that would be better as a separate NPM package. We've tried to keep the reporters bundled with the core library fairly basic so that we don't throw specialised reporters in with every download, as most people just aren't going to need them. 

If you'd like to have a go at writing a JUnit reporter, then one way of doing it might be to combine [this json to junit converter](https://www.npmjs.com/package/json-junit) with the JSON reporter included with Pa11y. If you were make a `pa11y-reporter-jsunit` available to other people on npm then anybody would be able to install it and run it with `pa11y --reporter jsunit`

(Also we have a CI test runner if you're interested 😄 https://github.com/pa11y/ci )

**Comment by rowanmanning** [comment]
I'm gonna close this, as we're not going to add to core. If somebody reads this and decides to create a separate reporter package then we'll definitely link out to it.

**Comment by macieklewkowicz** [comment]
For those who came here looking for a JUnit reporter for pa11y - I've created one: https://github.com/macieklewkowicz/pa11y-reporter-junit.

After installing with `npm install pa11y-reporter-junit` you can use it by running pa11y with the `-r junit` option.

**Comment by jorgetutor** [comment]
It seems this plugin is not compatible only with 5 versions, so not working on 6. I will open a new issue in the plugin
