### ISSUE TITLE
Allow sharing a Chrome browser instance between multiple test runs

### ISSUE THREAD

**Issue by rowanmanning** [pa11y/pa11y#298]
Currently we close and reopen headless chrome (in my branch anyway), which can be resource-intensive. Projects like Pa11y CI and Sidekick would benefit from being able to share the chrome browser instance between calls to `pa11y`.

**Comment by colinrotherham** [comment]
The new `browser.process()` method might help here.

I think our Chrome crashes are to do with Docker + memory or disk usage.

On a new Mac I can easily start off 30x `pa11y()` promises, but under Docker we're seeing Chromium crashes barely at 2x in parallel. Possibly due to https://github.com/GoogleChrome/puppeteer/commit/32a7fd5f37963dbe9d22f9a2976fc1e3a0c80700

Sharing the browser instance will definitely help.

**Comment by adgad** [comment]
This would be of interest to us on FT.com. We currently run a set of smoke tests on a set of URLs (which are in the process of being rewritten to use puppeteer v1), and then subsequently run pa11y on a subset of those URLs.

It would be nice to be able to do something like `pa11y(page, options)` - where `page` is the puppeteer page object.

I'd imagine this would require being on the same version of puppeteer though...

**Comment by majadinjar** [comment]
I need to write test cases for multiple urls, with must have actions before scanning any page. However, I can't find example with multiple urls and actions, so that they share same browser instance. I want to be able to login only in first case, and then just run tests on urls on same same application:
1. https://app.com/home
2. https://app.com/service
3. https://app.com/service/method
etc.
 without executing new browser instance for every page and logging in again. Is it possible with this version of pa11y?

**Comment by majadinjar** [comment]
> I need to write test cases for multiple urls, with must have actions before scanning any page. However, I can't find example with multiple urls and actions, so that they share same browser instance. I want to be able to login only in first case, and then just run tests on urls on same same application:
> 
> 1. https://app.com/home
> 2. https://app.com/service
> 3. https://app.com/service/method
>    etc.
>    without executing new browser instance for every page and logging in again. Is it possible with this version of pa11y?

Found it :) https://github.com/pa11y/pa11y/blob/master/example/puppeteer/index.js 

Works great.
