### ISSUE TITLE
Work out whether Headless Chrome has issues with iframes

### ISSUE THREAD

**Issue by rowanmanning** [pa11y/pa11y#300]
PhantomJS had issues with iframes, and there's a troubleshooting entry for it. I want to know if we can delete that entry now that we're moving to Headless Chrome.

**Comment by andrewmee** [comment]
Version 5 still appears to ignore any iframe contents at present.  Is this something we'd rather was included, or we're happy with current behaviour?

I'm a bit on the fence of whether this would be useful to change since I'd assume most iframe usage out there is to pull in 3rd party content and so any errors wouldn't be resolvable anyway?

**Comment by rowanmanning** [comment]
Oh cool, if that's the case then it's the same as with PhantomJS. I think it'll be best to leave it as-is. The only actionable item from this is to update the TODO entry in the troubleshooting guide

**Comment by manantrivedi** [comment]
Add argument in ChromeOptions,

chromeOptions.addArguments("--user-agent=New User Agent");

its work perfectly for me!

**Comment by shawbirendra** [comment]
Yes, it worked for me also but i have another issue with it.
suppose my base url is : **https://abc.com** 
which internally re-directing to another url : **https://xyz.com**
now with **header-less chrome driver**, it is not **re-directing** but with normal chrome driver, it is working fine.

any suggestions for this problem will be appreciated.
Thank you.
