### ISSUE TITLE
Work out Pa11y 4.x support timeline

### ISSUE THREAD

**Issue by rowanmanning** [pa11y/pa11y#308]
After the release of Pa11y 5.x, I think we need a longer support timeline for Pa11y 4.x.

Because [5.x](https://github.com/pa11y/pa11y/pull/286) currently drops support for Node.js 4–6, I feel like we should support the previous version for longer than our [usual 6 months](https://github.com/pa11y/pa11y#support-and-migration) (even if #307 happens, retaining Node.js 6 support).

It might make sense to align our end-of-support date for Pa11y 4.x with the [Node.js LTS schedule](https://github.com/nodejs/LTS#readme). Which could mean either:

  - April 2018 (if we support Node.js 6)
  - April 2019 (if we drop Node.js 6)

Support in this context could mean different things as well. Our normal end-of-life support includes only bug-fixes, but with a longer support time we may want to consider back-porting features. I see a few options:

  - We take our usual stance and only offer bug-fixes for Pa11y 4.x after 5.x is released
  - We back-port viable features for the first 6 months of the support period

What are people's thoughts?

**Comment by hollsk** [comment]
What sort of features would we backport? Are you thinking of things like Actions or... i don't know, the thing where we'd maybe want to remove reporters from the core lib and make them standalone packages? I'd support that to some extent, but I'd be less keen on backporting smaller things. 

Pa11y 5.x is very different under the hood to Pa11y 4.x and below, so the change will make a big difference to some users, especially if we go ahead with the plan in dropping `beforeScript`. We'd want to encourage people to move to Pa11y 5.x as soon as they can, and the best way to do that is to make the feature set better in the new version 😉 

We know that the tools are used by some pretty big organisations, and we also know (from experience!) that pretty big organisations can be slow to update codebases, so I think everyone would be grateful for a longer support period, even while we're pushing/encouraging people to switch to Pa11y 5.x.

**Comment by rowanmanning** [comment]
Yeah I'm not sure what things people will want backported, it's really hard to tell. It might be that a lot of people can just switch over no problem or it might take _ages_.

**Comment by andrewmee** [comment]
My inclination would be to stick to the usual support policy at least initially, and re-evaluate towards the end of that policy whether we want to extend it (based on user feedback/panicking/usage statistics, etc).

Similarly we can consider backporting on a case by case basis (and taking into account our time and other priorities) rather than blessing the 4.x branch with a blanket additional level of support.

I say all this as I think the current policy should be generous enough, and that we should be focusing our efforts primarily on moving forwards rather than potentially spending a lot of time supporting old software (with potentially limited benefit to users if people can upgrade promptly).

**Comment by rowanmanning** [comment]
OK I'm up for that. So specify the normal 6 months but we'll review in 4 months or so? I can add a note to the README explaining this.
