### ISSUE TITLE
How do i set up pa11y to test an Angular 4 app ? 

### ISSUE THREAD

**Issue by jachep** [pa11y/pa11y#333]
running pa11y on my localhost but it is just testing the index.html contents, it is ignoring all the router generated content and also the app-root ? any help would be appreciated !

**Comment by rowanmanning** [comment]
Hi @jachep, this is probably because Pa11y runs the tests before the content is generated. You could try either using the [`wait` option](https://github.com/pa11y/pa11y#wait-number) or [specify some actions](https://github.com/pa11y/pa11y#actions).

Pa11y runs the tests immediately after page load by default. The above configurations will delay the test running while your app gets set up.
