### ISSUE TITLE
Incorrect error of: Duplicate id attribute value "" found on the web page 

### ISSUE THREAD

**Issue by jlsorak** [pa11y/pa11y#350]
The error is caused by some 3rd-party scripts that are injecting additional scripts with an empty id attribute. They look like this in the devtools:

<img width="627" alt="screen shot 2017-11-17 at 12 16 01" src="https://user-images.githubusercontent.com/25332734/32946851-227ababc-cb91-11e7-9db8-fa348d016912.png">

It's causing Pa11y to identify these as erroneous elements.

**Comment by rowanmanning** [comment]
Hi @jlsorak, this is expected behaviour as those are still duplicate `id` attributes – they're just both empty. If you run the following through the [HTML Validator](https://validator.w3.org/nu/#textarea) then it will outline the issues:

```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Example</title>
    </head>
    <body>
        <div id>div with empty id</div>
        <div id>div with empty id</div>
    </body>
</html>
```

Pa11y can't really make exceptions on this, and the code in your page is technically invalid 🙂 would it be possible to speak to the third parties in question and mention that they're adding invalid HTML to your pages?
