### ISSUE TITLE
Add an example of running code before Pa11y 5.x

### ISSUE THREAD

**Issue by rowanmanning** [pa11y/pa11y#383]
Possibly now that we support passing in a `browser` and `page` option, we should add an example of making changes to the page before running Pa11y.

This could result in similar support issues as with `beforeScript` but users can already do this with Pa11y 5.x and maybe it's better for us to hand-hold a little. The documentation on `brower` and `page` options is more explicit about the level of support you'll get if you're adding your own code.

**Comment by mayankagarwal8188** [comment]
Hi,

I am using pa11y beta version - 5.0.0-beta.8

I have added an action :
set field input to "value"

But the problem I am facing is on input I am clicking on a button which gets enabled on input keyup event or when the user types in the values. So I am not able to test this scenario, Since the button is not getting enabled as it is just setting the value to the input field and dispatching the input event from action.

Is there any way we can trigger keyup or any other events when setting a value to input field ?

**Comment by andrewmee** [comment]
At the moment pa11y executes a [`goto` action on the page](https://github.com/pa11y/pa11y/blob/5.x/lib/pa11y.js#L166) even when `page` is provided as an option.

If we want to allow manipulation of the page before pa11y runs, I presume we'll need to change this otherwise that `goto` action would wipe out any manipulations after it reloads the page.

Do we definitely want to add this functionality?

**Comment by mayankagarwal8188** [comment]
I needed this functionality because I wanted to somehow call the keyup event while setting the input field value so that the other fields gets enable and my rest of the wait and actions will execute. 

It's not possible for us to change the application logic, since it is taking the default functionality of bootstrap input and we are enabling the submit button once input validates. And it use to get stuck on wait action of that button.

Please let me know if there is any other solution to call the keyup or letdown any keyboard type event via pa11y.

**Comment by rowanmanning** [comment]
@andrewmee yeah I agree, maybe we should revisit later, gonna move out of the 5.0 release milestone and we can address once that's stable.

@mayankagarwal8188 we could possibly add an "emit event" action which will allow you to fire the event you need. I'll investigate further tomorrow

**Comment by v-andrew** [comment]
@rowanmanning @andrewmee Is there any progress for this issue?

I need a way to skip `await page.goto(url, gotoConfig);`. Is it possible to add a parameter for that?

**Comment by v-andrew** [comment]
> 
> 
> @rowanmanning @andrewmee Is there any progress for this issue?
> 
> I need a way to skip [`await page.goto(url, gotoConfig);`](https://github.com/pa11y/pa11y/blob/5.x/lib/pa11y.js#L166).
> Is it possible to add a parameter for that?

Just found `ignoreUrl` which does what I want.

**Comment by josebolos** [comment]
Seeing as this hasn't cropped up again, I'm going to close this issue, as it would only add more maintenance work for us.
