### ISSUE TITLE
Not detecting the input change event or keyup event on set field action in angular 2

### ISSUE THREAD

**Issue by mayankagarwal8188** [pa11y/pa11y#384]
Hi,

I am using pa11y beta version - 5.0.0-beta.8

I have added an action :
set field input to "value"

But the problem I am facing is on input I am clicking on a button which gets enabled on input keyup event or when the user types in the values. So I am not able to test this scenario, Since the button is not getting enabled as it is just setting the value to the input field and dispatching the input event from action.

Is there any way we can trigger keyup or any other events when setting a value to input field ?

@rowanmanning

**Comment by andrewmee** [comment]
Hi @mayankagarwal8188,

I would recommend that you update your application to be triggered on the `input` event, rather than (or in addition to) `keyup`.  This would also make your app more robust, as it's possible to add text into an input without ever triggering a keyup event (e.g. when a field is autofilled).

When pa11y changes the state of fields within an application, it [triggers the appropriate event](https://github.com/pa11y/pa11y/blob/5.x/lib/action.js#L97) for that change of state ([an `input` event](https://developer.mozilla.org/en-US/docs/Web/Events/input) in the case of a text input).  

We don't throw keyboard events as a keyboard has not been used, and it would be impossible for us to anticipate what keyboard events may trigger in the application being tested.
