### ISSUE TITLE
Is it intended for actions to be done *after* navigating to test page

### ISSUE THREAD

**Issue by chrisnye** [pa11y/pa11y#456]
As preface, I've previously mostly worked on automated web app functional testing (protractor, Selenium) and I'm new to accessibility testing.  I have been attempting to integrate accessibility checks using pa11y into our build process.

Why are the set of actions performed after navigating to the page under test with (as far as I can tell) no mechanism for returning to it?

Would it be possible / desirable to either:

- Move the "page.goto(url, gotoConfig)" in pa11y.js to execute after the "Run actions" block.  This would allow a common set of actions to apply to any test URL regardless of the ending page of those actions.
- Add a new action similar to 'navigate-url' that returns to the page under test.  

The only workaround I've been able to find is to have a custom options object for each URL under test where the only difference is at the final step the navigate-url action has a different parameter.  We would rather have a single common options block used for all urls, especially as our next step is to set up a pa11y-ci runner.

**Comment by thibaudcolas** [comment]
Hey @sciguyCO 👋 The point of actions as I understand them is to interact with the page – how would that be possible if the page wasn't loaded yet? What else would you want to use actions for before the page has been navigated to?

**Comment by sciguyCO** [comment]
@thibaudcolas Well, that's what I'm trying to wrap my head around.

As an example, we want to use pa11y to verify accessibility on a "account profile" information page.  That page requires going through login.  Based on my investigation, it seemed that I am to use actions to go through the login process to set the browser state to get to the point of the accessibility verification on the page under test.

That's all fine, but the after completing the login actions my test needs to "navigate to to /profile" to get to the page I really want to verify.  Now I'm done with that page and now want to verify the "email options" page.  I can't re-use the actions from before as a predefined configuration because that last step now needs to be to "navigate to /email-options".

So if our team wants to verify the full site map of our web application using pa11y (most of which is only accessible after login), we need to define a unique options block for each page where the only variation is the final step of the actions array.

I was curious whether a more modular method existed so that the actions block acts as a generic "beforeScript" that gets applied to every page under test.

I may just be attempting to use pa11y in a way it's not intended for.

**Comment by thibaudcolas** [comment]
Good question! I don't think the current Pa11y API/config is well suited for UIs behind authentication (https://github.com/pa11y/pa11y/issues/188#issuecomment-481201211, #450), but my use case is quite similar so I can at least share how I've tried to solve it.

For me it's all the UI that's behind login, not just some of the pages, so it wasn't desirable to have every single test log in separately – that would make the whole test suite 2x slower. So instead, I've used Puppeteer like Pa11y would to log into the site once, and retrieve the session cookie:

https://github.com/thibaudcolas/wagtail-tooling/blob/8663e51c2a395688e6fefd9e3156d5b5ae92bff8/accessibility/pa11y-test.js#L80-L88

Then, for subsequent tests, the cookie is set in the HTTP headers and also set directly in the browser: https://github.com/thibaudcolas/wagtail-tooling/blob/8663e51c2a395688e6fefd9e3156d5b5ae92bff8/accessibility/pa11y-test.js#L141-L148 This is to circumvent the limitations described in #450.

----

Otherwise, something that could work for you is to define your scenarios in JS code and use the Pa11y JS API instead of the CLI, so reusing the same actions between scenarios is more straightforward.

**Comment by joeyciechanowicz** [comment]
Thanks for raising this issue @chrisnye, and @thibaudcolas for your responses already.

Pa11y is meant as a "one-shot" kind of tool, and as thus the actions are intented to all be run before testing.

You can pass in HTTP headers (such as with a session cookie) so that you can avoid all the actions to _login_ for each test.

The other option is to call `pa11y` with a pupetter `browser` and `page` instance you have set up yourself.
