### ISSUE TITLE
 indicating error for action: navigate to

### ISSUE THREAD

**Issue by aastrong** [pa11y/pa11y#479]
I am using the Pa11y Dashboard to run this Pa11y Scan. 
When I use the action "navigate to" - I always get the error 

> Error: Invalid action: "navigate to my.url.com"

I believe this issue is coming straight from Pa11y, and not from Pa11y Dashboard. 

## Expected behaviour
For the "Navigate to" action to function

## Actual behaviour
It's not working

## Steps to reproduce
Create actions on a pa11y check with the "navigate to" URL - here is my example

wait for url to be my.url.com
set field #user_id to 12345
set field #pass to ABCDE
click element #login-btn
wait for url to be my.logged-in.url.com
navigate my.other.url.com

**Comment by joeyciechanowicz** [comment]
Can you try with a full url, including the protocol.

`navigate to https://my.other.url.com/`

**Comment by aastrong** [comment]
@joeyciechanowicz It is using the full protocol, sorry I didn't include that in the example.

**Comment by josebolos** [comment]
Hi @aastrong,

Unfortunately we're not able to reproduce this problem. Is the script above the one you're actually using? It should say "navigate to" instead of "navigate".

Have you tried taking screenshots between the different steps in order to make sure that all the actions specified are correct?

If not, could please add the following information to the issue, so we can try to reproduce it? Please include:

* The actual script that you're using
* The result of running `pa11y --environment`

Thanks!

**Comment by aastrong** [comment]
@josebolos 
Sorry, that is my bad. 

I am using the "navigate to" - was a typo when creating the issue. 

I can't give the exact actions, as it would be giving away client information that I cannot do right now. 

I'll try running pa11y --environment, and also try the individual actions.
Like i said, im using the pa11y dashboard right now, but the error "appeared" to be coming from straight up Pa11y. 

Will respond shortly.

**Comment by aastrong** [comment]
@josebolos I've tested using just pa11y locally ( no dashboard ) - and it works fine - so the issue is not with this repo.

Thanks for your time.

**Comment by aastrong** [comment]
Also, for anyone else looking - the issue was that we had version 2.2.2 of the Pa11y Dashboard installed, which ran with Pa11y 4. 

the "navigate to" action was only introduced in pa11y 5.
So we're updating our dashboard :)

Cheers.
