### ISSUE TITLE
CLI: Running pa11y on multiple files in a local directory using a glob pattern

### ISSUE THREAD

**Issue by s-g-k** [pa11y/pa11y#525]
Hello! 

I'm having some issues when I try to run pa11y on a directory of html files. I was expecting to be able to use a glob pattern like `./dist/**/*.html`. 

If I run `pa11y ./dist/**/*.html` it produces an error.

If I run `pa11y ./dist/*.html` when there is only a single html-file in dist, it runs pa11y on the file. However, if there are muliple files, ie. index.html and about.html I don't even get an error. Pa11y just presents me with the help menu.

Maybe this is expected behaviour, or is it a feature request? It would be great to be able to run this on a directory as part of a build step. 

---

## Expected behaviour
When I run `pa11y ./dist/**/*.html` I expect it to run on all files in subfolders of dist.
If I run 

## Actual behaviour
I get an error, `Error: net::ERR_FILE_NOT_FOUND at file://~/dist/**/*.html`

## Steps to reproduce

Run `pa11y ./directory_of_multiple_files/**/*.html` 

## Environment:
```
Pa11y:      5.3.0
Node.js:    12.9.1
npm:        6.14.5
OS:         19.4.0 (darwin)
```

**Comment by josebolos** [comment]
Hi @s-g-k,

Thanks for creating such a detailed issue!

Unfortunately, this is expected behaviour. For historical reasons, `pa11y` is a single-use command that will run a test on one URL or file and exit. It won't accept a list of URLs or pages. If you want to run `pa11y` on several pages, you will need to launch an instance of pa11y for each page that you want to test.

That said, there's another tool based on pa11y [(pa11y-ci)](https://github.com/pa11y/pa11y-ci) which is built with continuous integration in mind and it allows you to run tests on a number of pages.

CLI options should be similar so just replacing `pa11y` with `pa11y-ci` is all that you should need!

Please let me know if that's not the case.

**Comment by s-g-k** [comment]
Thank you for a great reply too. I thought this might be the case, and thank you for pointing me in the right direction. 

`pa11y-ci` doesn't support exactly the same command line arguments, but it's possible to specify the options in a configuration file. I got it up and running nicely. 

If anything, this issue can be a pointer for anyone searching this repo for glob or multiple files.
