### ISSUE TITLE
Pa11y timeout issue 

### ISSUE THREAD

**Issue by sowmyasridharamurthy** [pa11y/pa11y#540]
**Please note:** This repository's issues are reserved for feature requests, bug reports, and other issues with the Pa11y library itself.

If you need help integrating Pa11y with your application, we recommend using [Stack Overflow](https://stackoverflow.com/questions/tagged/pa11y).

For a bug report, please use the template below:

---

## Expected behaviour
pa11y  to execute tests for the url mentioned

## Actual behaviour
throwing timeout error

## Steps to reproduce
1. install nodejs
2. create new folder
3. execute pa11y installation command : npm install -g pa11y (followed the steps mentioned in https://github.com/pa11y/pa11y)
4. execute the test command : pa11y https://mail.google.com

## Environment:

![image](https://user-images.githubusercontent.com/35350156/99245281-9da85600-2803-11eb-9fb1-2b430aa44970.png)

**Comment by kkoskelin** [comment]
Can you include output from `pa11y --debug <url>`?

**Comment by sowmyasridharamurthy** [comment]
Hi kkoskelin,

please see the output below 

![image](https://user-images.githubusercontent.com/35350156/99284137-31931580-2836-11eb-9d42-3e5050d7ce77.png)

**Comment by kkoskelin** [comment]
I'm concerned this might be rather difficult to debug further, but I have a few thoughts.
1) do you get similar timeout issues with other URLs? for example https://pa11y.org/ ?
2) Is there anything else in your `pa11y-1/` folder, and how did you install `pa11y`?  Did you simply `npm install -g pa11y` followed by the invocation we see in the screenshots?
3) Is there any difference if you use the javascript interface as shown in https://github.com/pa11y/pa11y#javascript-interface ?

I'm getting the feeling there's something about a combination of your platform and installation that is causing the issue, but I can't put my finger on it.  As a MacOS user, I installed the latest and tried the same query and URL without any issues.

**Comment by sowmyasridharamurthy** [comment]
yes Kkoskelin, i simply followed the instruction in readme.md file in github. 

Which is your point number 2
"simply npm install -g pa11y followed by the invocation we see in the screenshots?"

Pardon if i sound too stupid, am i missing anything here?

**Comment by kkoskelin** [comment]
No insult intended, I assure you.  Regarding 2), I now understand better.  Have you tried 1) or 3) yet?
I'm feeling out of my depth, and wondering if one of the project maintainers may have an idea.

**Comment by kailynnelson** [comment]
I'm having the same issue 

![image](https://user-images.githubusercontent.com/22021550/112246120-631a5400-8c0f-11eb-981c-e13d60eabeeb.png)

**Comment by kailynnelson** [comment]
Both when installed locally in a project and when installed globally

**Comment by kailynnelson** [comment]
> Can you include output from `pa11y --debug <url>`?

Here is my output when running with `--debug`:

![image](https://user-images.githubusercontent.com/22021550/112246295-aaa0e000-8c0f-11eb-9f23-39b881b995b4.png)

**Comment by josebolos** [comment]
Hi @sowmyasridharamurthy and @kailynnelson 

Thanks for creating the issue, and apologies for not getting back to you earlier.

From looking at your screenshots I can see two issues that may or may not be related.

Regarding the `'taskkill' is not recognized as an internal or external command` error message, none of the core developers have a Windows machine at hand in order to debug this, but it looks like you may be experiencing a bug that occurs when running Node.js applications that use puppeteer on certain Windows environments. It looks like puppeteer tries to use `taskkill` when closing the browser but is unable to find `taskkill`, maybe because the `taskkill` application is not available in the `PATH`.

A summary of this issue can be found here can be found in the Puppeteer issues [(#1533)](https://github.com/puppeteer/puppeteer/issues/1533), specifically [in this comment](https://github.com/puppeteer/puppeteer/issues/1533#issuecomment-521163737).

It may be worth trying from a different terminal (CMD / PowerShell) and see if that makes a difference, or alternatively checking for the presence of `taskkill` on your `PATH`.

The second issue, which may or may not be related to the first one, is the timeout. This is expected behaviour from pa11y if the site takes too long to respond. The timeout by default is set to 30 seconds so I would suggest trying to increase the timeout first to something like 120 seconds and see if that makes a difference.

It may be that the timeout may somehow be caused by puppeteer's confusion around `taskkill`, but I rather make sure it's not just a site being slow.

I hope this helps. Please do let me know if it doesn't.

**Comment by kailynnelson** [comment]
> I hope this helps. Please do let me know if it doesn't.

Thank you, @josebolos! Running as administrator from Powershell worked (not as non-admin). 

![image](https://user-images.githubusercontent.com/22021550/112775483-da762c00-8ff1-11eb-9fbb-71b0d38524f1.png)

**Comment by chaochungtsai** [comment]
Hello, please let me know if I should start a new issue:
I am also having timeout errors, almost always with actions when waiting for element to be visible
![image](https://user-images.githubusercontent.com/22780337/119182967-4ab89100-ba28-11eb-81c4-6ab2605aaa41.png)

In my configuration I have:

>  "timeout": 120000,

**Comment by hollsk** [comment]
Hi @chaochungtsai - thanks for using Pa11y! It'll be easier for us if you open a new issue for this. 

For what it's worth, I checked the URL that you've given in the `navigate to` action, and I get redirected to an eauthentication page that doesn't seem to have an `#email` element on it, which may be why Pa11y is failing at that point. But do please open a new issue so we can help you separately 😄  

Thanks again!

**Comment by chaochungtsai** [comment]
@hollsk Apologies for the dumb mistake, and thank you so much.

**Comment by josebolos** [comment]
For the original reporter, we just released version 6 of pa11y which has a more resilient handling of the browser, please give it a try and feel free to reopen the issue if it's still happening.
