### ISSUE TITLE
Is there any way where i can add explicit wait in actions ?

### ISSUE THREAD

**Issue by zetendra** [pa11y/pa11y#542]
In my application, wait for an element is not working properly. Page is not loading properly, i need to add a sleep in actions. Is there a way ?

**Comment by kkoskelin** [comment]
You should probably utilize the `timeout` parameter, although take note that the timeout applies to the test in its entirety, not to individual actions.
Additionally, you might consider waiting for intermediate elements or parent elements which will contain the element you are eventually expecting to render.
If this doesn't work, you ought to be absolutely sure that the page does indeed eventually render the things you're expecting, perhaps by navigating to the initial URL and then replicating the actions and waits you've specified.

**Comment by zetendra** [comment]
Thank you @kkoskelin for the quick response, but page has animated divs. I need to wait until the those are rendered

**Comment by kkoskelin** [comment]
I have not seen your code nor your page, but at the risk of my own misunderstanding, it seems to me that if you have a webpage that has over 30 seconds of animations, it may NOT, in fact, be accessible.

I do not know how much control you have over the application that creates or serves the page, but I wonder if you are able to set a flag in the query string or in headers -- something that would bypass the very long wait for animations.

The other option would be to provide screenreader-only controls in the application which allow the user to bypass the animations. Something like this might be helpful:

```
.screenreader-only {
  position: absolute;
  left: -999em;
}
```
Otherwise if you are able to provide example code / links we may be able to discuss further.

**Comment by josebolos** [comment]
I'm guessing this is now fixed, please feel free to reopen and include specific details of the failing action if it's not. Thank you!
