### ISSUE TITLE
Getting timeout error everytime i use actions

### ISSUE THREAD

**Issue by vaibhooo** [pa11y/pa11y#547]
Hi Team 

I am trying to run action in pa11y  for a site that requires login .When  I am doing login I am getting timeout error .Below is the json attached

{
	"urls": [{
		"url": "https://tst.bcom3test.com/app",
		"actions": [
			"set field #i0116 to martstuser15@publicisgroupe.net",
			"click element #idSIButton9",
			"set field #i0118 to 7Eh.5)Jk8B",
			"click element #idSIButton9",
			"wait for url to be https://tst.bcom3test.com/app"
		],
		"timeout": 60000
	}]
}

Please see screenshot attached

![image](https://user-images.githubusercontent.com/78065197/105942487-5224ea80-6085-11eb-8910-169e5f5ed2c8.png)
![image](https://user-images.githubusercontent.com/78065197/105942670-b182fa80-6085-11eb-9cd4-4da30a67a11c.png)

**Comment by kkoskelin** [comment]
No disrespect intended -- have you tried to manually carry out the actions you've provided in your configuration?  It seems that they're all working except for waiting for the url.  

I'm also wondering if your app is changing its url as you load it -- perhaps a trailing slash, or a fragment, or something else.  As your final action, have you considered `wait for path to be /some-path` rather than waiting for a url?  Good luck.

**Comment by cmuncharaz** [comment]
Waiting for the username input field to be removed makes sure that the actions run as expected, without resulting in a timeout.

```
"set field #i0116 to martstuser15@publicisgroupe.net",
"click element #idSIButton9",
"wait for element #i0116 to be removed",
"set field #i0118 to 7Eh.5)Jk8B",
"click element #idSIButton9",
"wait for url to be https://tst.bcom3test.com/app"
```

**Comment by hollsk** [comment]
Thanks @cmuncharaz ! 

@vaibhooo I'm going to close this issue now - please let us know if adding a `wait` between those two actions doesn't solve your problem, and we can revisit it. Thanks for using Pa11y!
