### ISSUE TITLE
New action type to "wait X" milliseconds

### ISSUE THREAD

**Issue by carlb0329** [pa11y/pa11y#565]
Feature Request: Wait for X number of milliseconds.

We've encountered an issue with trying to use actions to get to a specific step in a single page application.  We have been able modify the underlying pa11y library with a new action type to "wait 1000" or any number of ms.  This allows us to pause the pa11y actions queue for X milliseconds and allow our application to render.

We'd like to open a pull request for this new action type.  It's actually a pretty small code change to add the additional action handler.

```
// Action to wait a set amount of time in milliseconds
// E.g. "wait 1000"
{
   name: 'wait-time',
   match: /^wait (\d+)$/i,
   run: async (browser, page, options, matches) => {
      const milliseconds = matches[1];
      const date = Date.now();
      let currentDate = null;
      do {
         currentDate = Date.now();
      } while (currentDate - date < milliseconds);
   }
}
```

**Comment by devin-w-hill** [comment]
Hi, we're working on this together. Let us know what needs to happen in order to get this action included in pa11y.

**Comment by josebolos** [comment]
Hi @carlb0329, @devin-w-hill 

Thanks for creating this issue and apologies for the late reply.

The decision to not have an action in pa11y that waits for an specified amount of time is intentional. Pa11y already provides 3 different actions that can wait for certain events to happen:

* [Wait for Fragment/Path/URL](https://github.com/pa11y/pa11y#wait-for-fragmentpathurl)
* [Wait for Element State](https://github.com/pa11y/pa11y#wait-for-element-state)
* [Wait for Element Event](https://github.com/pa11y/pa11y#wait-for-element-event)

These three actions provide alternatives for SPAs that are much more robust than waiting for a specified amount of time. It also eliminates the variability from using specific waiting times: 5 seconds might be enough for my machine and internet speed, but what happens when the tests run in the slow free-tier of a cloud CI system?

If you can think of any examples that would be better solved using a specific waiting time instead of any of the three actions above, feel free to reopen this issue.
