### ISSUE TITLE
Pa11y check passes locally, fails in Github Actions

### ISSUE THREAD

**Issue by btylerburton** [pa11y/pa11y#654]
**This repository's issues are reserved for feature requests, bug reports, and other issues with the Pa11y library itself.**

If you need help integrating Pa11y with your application, we recommend using [Stack Overflow](https://stackoverflow.com/questions/tagged/pa11y).

For a bug report, please use the template below. To keep the backlog clean and actionable, issues may be immediately closed if they do not follow one this template.

---

## Expected behaviour
Pa11y checks passing locally should also pass in GH pipeline when no other issues, such as asset loading, are present.

## Actual behaviour
Pa11y-ci checks against URLs in our static site all pass locally with 0 errors, but fail in GH actions. 

Also, to note, that we can get them to pass by writing the styles explicitly into the page, but those same styles written into an external stylesheet cause Pa11y to fail.

## Steps to reproduce
- Run pa11y
- Fix suggested contrast errors by adding them to an external stylesheet
- Pass pa11y locally
- Execute some variation of the following command in Github Actions and see pa11y fail: 
  - `pa11y-ci --sitemap http://localhost:8080/sitemap.xml --sitemap-exclude \"/admin\"  --sitemap-find \"^/\" --sitemap-replace \"http://localhost:8080/\"`

## Environment
Local env:
```
 System:
    OS: macOS 12.5.1
    CPU: (8) x64 Intel(R) Core(TM) i7-8569U CPU @ 2.80GHz
    Memory: 252.13 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.15.0 - ~/.nvm/versions/node/v16.15.0/bin/node
    npm: 8.13.2 - ~/.nvm/versions/node/v16.15.0/bin/npm
  pa11y: 6.1.1

```

**Comment by aarongoldenthal** [comment]
Hi @btylerburton,

Pa11y-ci should definitely run in GH actions. Assuming the [linked PR above](https://github.com/GSA/datagov-11ty/pull/90) is for the project you're having issues with, and [this](https://github.com/GSA/datagov-11ty/actions/runs/2981366670) is an example of the failing GH action, it looks to me like it's most likely an issue with the actions script.

If I'm reading the code correctly, for a build:

- The `build` script runs the `assets:build` script and an eleventy build
- The `assets:build` script writes the static assets to the eleventy output folder (`_site/assets/`), and writes the file locations to `_data/assetPaths.json`. The `_data/assetPaths.json` is saved in the git repository, but the other assets are not.
- The eleventy templates use the data from `assetPaths` to reference the appropriate files (in this case `styles.css`)

In `accessibility_scan.yml`:

- The `steps` include the standard checkout and install Node, then runs `npm install` and `npm run pa11y-ci:gh`
- The `pa11y-ci:gh` script run the `start` script, which performs an eleventy build and starts the server. The `_data/assetPaths.json` is in the git repository, so those CSS file locations are written to output HTML files. But, the CSS assets themselves are not in the git repo, and nothing in the eleventy config or script appears to call `./config/buildAssets.js`.
- Then the `pa11y-ci` script runs and fails because the pages aren't loading the CSS files.

I expect if you do a fresh clone of the repository and run the specific action steps, the page you open will show that it's failing to load the CSS. So, it looks like you need to run the `assets:build` script before `start` and `pa11y-ci`.

**Comment by btylerburton** [comment]
Oh wow! Thanks for the detailed answer @aarongoldenthal. Pa11y is now reporting the same in CI as it is in my local, so I'm going to close this issue.

**Comment by aarongoldenthal** [comment]
Glad it helped @btylerburton
