### ISSUE TITLE
timeout error for a single url

### ISSUE THREAD

**Issue by LuciaLux** [pa11y/pa11y#658]
I get a timeout error from pa11y when I try to send the command:

`pa11y https://www.difesa.it/Pagine/default.aspx`

this problem is only for this link. In fact, even on the other pages of the site, pa11y works normally.
I would like to understand what it is due to and a way to solve it.
---

## Actual behaviour
```
Welcome to Pa11y

 > Running Pa11y on URL https://www.difesa.it/Pagine/default.aspx

Error: TimeoutError: Pa11y timed out (300000ms)
    at Timeout.<anonymous> (C:\Users\39333\AppData\Roaming\npm\node_modules\pa11y\node_modules\p-timeout\index.js:39:64)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
```
## Steps to reproduce
```
pa11y https://www.difesa.it/Pagine/default.aspx
```
## Environment
 
```
 System:
    OS: Windows 10 10.0.19044
    CPU: (4) x64 Intel(R) Core(TM) i5-5300U CPU @ 2.30GHz
    Memory: 2.57 GB / 7.70 GB
  Binaries:
    Node: 16.15.0 - C:\Program Files\nodejs\node.EXE
    npm: 8.5.5 - C:\Program Files\nodejs\npm.CMD
  pa11y: 6.2.3
```

**Comment by josebolos** [comment]
Ciao @LuciaLux!

Thank you for creating this issue. I can replicate it successfully with both the axe runner, and the default HTML CodeSniffer, but the problem doesn't seem to happen every time, only about 50% of the time.

As I was suspecting that there's something wrong with the page, I tried to run a performance test using WebPagetest, you can see the results here:
https://www.webpagetest.org/result/221021_BiDc1X_A58/

From the 9 times that WPT tried to load the page, it didn't manage to load it successfully not even once, as shown by the following error message:

> (Test Error: Page Load Timeout)
> (Error: Timed Out)

I can see that the page has loads of different CSS and JS resources that would probably be more performant if they were concatenated and served as a single request. I can't see the load even being fired on any of the 9 page loads, so if I had to take a guess at where the problem may lie, I would say that there's probably some kind of JS task being run that is preventing the page to finish loading successfully and firing the load event. There's also a bunch of requests to `pbs.twimg.com` being fired. All this could be causing puppeteer (the library that pa11y uses to interact with browsers) to think that the page is still loading, until it finally reaches the 30s set up as the default timeout.

It could be useful to increase the timeout to a much higher value (e.g. 300s) and see if that makes a difference but, other than that, the only way to really fix the problem is probably by finding out what's causing the page to be so busy and delay the load event.

I hope that this helps!
